export const DOG_CONTEXT_ACTIONS = {
	SET_LOGGED_IN: 'SET_LOGGED_IN',
	SET_USER_INFO: 'SET_USER_INFO',
	SET_DOG_SEARCH_RESPONSE: 'SET_DOG_SEARCH_RESPONSE',
	SET_SELECTED_FAVORITES: 'SET_SELECTED_FAVORITES',
} as const;
